source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins
gem "jekyll", ">= 3.6.3"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem 'jekyll-mentions'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem "nokogiri", ">= 1.10.4"
gem "rubyzip", ">= 1.3.0"
